sudo: required
services:
  - docker

before_install:
  - docker build -t ret83/react-test -f ./react-client/Dockerfile.dev ./react-client

script:
  -  docker run -e CI=true ret83/react-test npm run test -- --coverage

after_install:
  - docker build -t ret83/multi-client ./react-client
  - docker build -t ret83/multi-server ./server
  - docker build -t ret83/multi-wroker ./worker
  - docker build -t ret83/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ret83/multi-client
  - docker push ret83/multi-server
  - docker push ret83/multi-worker
  - docker push ret83/multi-nginx